name: llama-russian

services:
    app:
        build: .
        volumes:
            - .:/app:z
            - /home/serhii/models/SambaLingo-Russian-Base.Q8_0.gguf:/model/SambaLingo-Russian-Base.Q8_0.gguf:z
        tty: true
        restart: unless-stopped
