services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - app-network
        ports:
            - "8080:8080"
        links:
            - db
        depends_on:
            db:
                condition: service_healthy

    db:
        container_name: db
        image: mysql:8.0
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: crud
        ports:
            - "1934:3306"
        volumes:
            - ./db/storage:/var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 30s

networks:
    app-network:
        driver: bridge